name: odyss
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  intl_phone_field: ^3.2.0
  flutter_native_splash: ^2.4.6
  flutter_multi_formatter: ^2.6.0
  mask_text_input_formatter: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/trans_logo.png
    - assets/images/intoimg1.png
    - assets/images/introimg2.png
    - assets/splash/splash.png
    - assets/logo/logo_white.png
    - assets/logo/app_icon.png
    - assets/logo/app_icon_white.png
    - assets/splash/Solid_black.png
    - assets/logo/square-xxl.png
    - assets/icons/active_chat_icon.png 
    - assets/icons/active_explore_icon.png.png 
    - assets/icons/active_rides_icon.png 
    - assets/icons/chat_icon.png 
    - assets/icons/curate_icon.png 
    - assets/icons/explore_icon.png 
    - assets/icons/profile_icon.png 
    - assets/icons/make_payment_icon.png 
    - assets/icons/rides_icon.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/static/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/static/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/static/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/static/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/montserrat/static/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/montserrat/static/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/static/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/static/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/static/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/montserrat/static/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/static/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
# flutter_native_splash:
#   image: "assets/splash/splash.png"
#   color: "FFFFFF" 
#   android: true
#   ios: true
#   fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/logo/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/splash/splash.png"
  background_image_dark: "assets/splash/splash.png"
  android_12:
    color: "#FFFFFF"              
    icon_background_color: "#FFFFFF"
    image: assets/logo/square-xxl.png

    color_dark: "#000000"
    icon_background_color_dark: "#000000"
    image_dark: assets/splash/Solid_black.png
    branding: null