import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:odyss/data/models/user_model.dart';

final userListProvider = Provider<List<UserModel>>(
  (ref) => [
    UserModel(
      id: 'xxxx1',
      nickName: 'Tumi',
      firstName: 'Tumilayo',
      lastName: 'Adeoluwa',
      middleName: 'Ayobami',
      video: '',
      picture: '',
      number: '',
      email: 'tumiadeoluwa@gmail.com',
      vibes: ['friendly', 'easy-going', 'sing-along'],
      rides: [],
      bio:
          'Hi, I am Tumi and I love fun trips with folks I vibe with, I also love making friends.',
      x: '@tumirants',
      fb: 'https://facebook.com/tumiadeoluwa',
      tiktok: '@tumi',
      insta: '@tumi002',
      password: 'Tumi1Adeoluwa',
    ),
    UserModel(
      id: 'xxxx2',
      nickName: 'Glory21',
      firstName: 'Glory',
      lastName: 'Johnson',
      middleName: 'Emilia',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx3',
      nickName: 'Tosi',
      firstName: 'Tosi',
      lastName: 'Kosisochukwu',
      middleName: 'Chinelu',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx4',
      nickName: 'Banjo',
      firstName: 'Banjo',
      lastName: 'Adewale',
      middleName: 'Kemi',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx5',
      nickName: 'Ayobams',
      firstName: 'Ayobami',
      lastName: 'Joshua',
      middleName: 'tade',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx6',
      nickName: 'Rex',
      firstName: 'Remi',
      lastName: 'Tunji',
      middleName: 'Lawale',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx7',
      nickName: 'Don',
      firstName: 'Donald',
      lastName: 'Blake',
      middleName: 'Fayemi',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx8',
      nickName: 'Tess',
      firstName: 'Tesbiyu',
      lastName: 'Olatunji',
      middleName: 'Raman',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
    UserModel(
      id: 'xxxx9',
      nickName: 'Princess',
      firstName: 'Princess',
      lastName: 'Egbunike',
      middleName: 'Favour',
      video: '',
      picture: '',
      number: '',
      email: '',
      vibes: [],
      rides: [],
      bio: '',
      x: '',
      fb: '',
      tiktok: '',
      insta: '',
      password: '',
    ),
  ],
);
